# basic site config
title: My Learning Site
description: Records of my learning path
baseurl: ""
url: "https://lizzietang.github.io"

# theme config
remote_theme: just-the-docs/just-the-docs
search_enabled: true
heading_anchors: true

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

nav_enabled: true

# Show navigation error report
nav_error_report: true # default is false/nil.

# navigation config
aux_links:
  "My GitHub":
    - "https://github.com/LizzieTang"
aux_links_new_tab: true

# footer congig
footer_content: '© 2026 My Learning Site'

# github edit config
gh_edit_link: true
gh_edit_repository: "https://github.com/LizzieTang/lizzietang.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# 插件
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
